"""
Trade Reconciliation Analysis for V14 PM
=========================================
Identifies genuine vs phantom trades by cross-referencing trades.csv
against the bot's known runtime windows from the log.

READ-ONLY: Does not modify any files. Outputs a report.
"""
import csv
from datetime import datetime, timezone

TRADES_CSV = "trading/spot/paper/v14_portfolio/trades.csv"

# Known runtime windows from bot.log analysis:
#
# Window 1: First legitimate FRESH start
#   Start: 2026-03-06 08:04 UTC (FRESH mode, engines created, candle processing began)
#   End:   2026-03-08 18:00 UTC (first restart by Gee Gee for equity fix)
#   Status: GENUINE — bot ran continuously for ~58 hours
#
# Window 2+: March 8 18:00 onwards — chaos
#   Multiple restarts (with and without --fresh)
#   Non-fresh restarts backfilled Feb 28 - Mar 9, generating phantom trades
#   --fresh restarts ALSO triggered backfill via rebalance path (bug)
#   Rebalance was firing every 5 minutes instead of daily (bug)
#   Cannot trust ANY trades from this period
#
GENUINE_START = datetime(2026, 3, 6, 8, 4, 0, tzinfo=timezone.utc)
GENUINE_END = datetime(2026, 3, 8, 18, 0, 0, tzinfo=timezone.utc)

def parse_ts(s):
    return datetime.fromisoformat(s)

def analyze():
    with open(TRADES_CSV) as f:
        trades = list(csv.DictReader(f))
    
    genuine = []
    phantom = []
    borderline = []
    
    for t in trades:
        open_t = parse_ts(t["open_time"])
        close_t = parse_ts(t["close_time"])
        
        # Trade is genuine only if both open AND close fall within the clean window
        if open_t >= GENUINE_START and close_t <= GENUINE_END:
            genuine.append(t)
        # Trade opened in clean window but closed after (could be replayed close)
        elif open_t >= GENUINE_START and open_t <= GENUINE_END and close_t > GENUINE_END:
            borderline.append(t)
        else:
            phantom.append(t)
    
    print("=" * 80)
    print("  V14 PM Trade Reconciliation Report")
    print("=" * 80)
    print(f"\nClean runtime window: {GENUINE_START.isoformat()} to {GENUINE_END.isoformat()}")
    print(f"Total trades in CSV: {len(trades)}")
    print()
    
    print(f"GENUINE trades (both open+close in clean window): {len(genuine)}")
    genuine_pnl = sum(float(t["pnl"]) for t in genuine)
    print(f"  Realized PnL: ${genuine_pnl:.2f}")
    if genuine:
        print(f"  Win rate: {sum(1 for t in genuine if float(t['pnl']) > 0) / len(genuine) * 100:.0f}%")
        print(f"  Symbols: {sorted(set(t['symbol'] for t in genuine))}")
    print()
    
    for t in genuine:
        print(f"  [OK] #{t['deal_id']:>3} {t['symbol']:<14} {t['open_time'][:16]} -> {t['close_time'][:16]}  "
              f"L{t['layers']} ${float(t['invested']):>8.2f} -> ${float(t['pnl']):>+7.2f} ({t['return_pct']}%)")
    
    print(f"\nBORDERLINE trades (opened in window, closed after): {len(borderline)}")
    borderline_pnl = sum(float(t["pnl"]) for t in borderline)
    print(f"  Realized PnL: ${borderline_pnl:.2f}")
    print(f"  NOTE: These opened legitimately but the close was replayed by a restart.")
    print(f"  The trade DID happen, but the exact close price/time may differ from")
    print(f"  what would have occurred if the bot had run continuously.")
    print()
    
    for t in borderline:
        print(f"  [??] #{t['deal_id']:>3} {t['symbol']:<14} {t['open_time'][:16]} -> {t['close_time'][:16]}  "
              f"L{t['layers']} ${float(t['invested']):>8.2f} -> ${float(t['pnl']):>+7.2f} ({t['return_pct']}%)")
    
    print(f"\nPHANTOM trades (outside clean window): {len(phantom)}")
    phantom_pnl = sum(float(t["pnl"]) for t in phantom)
    print(f"  Realized PnL: ${phantom_pnl:.2f}")
    print(f"  These were generated by backfill replays during restarts.")
    print()
    
    for t in phantom:
        print(f"  [XX] #{t['deal_id']:>3} {t['symbol']:<14} {t['open_time'][:16]} -> {t['close_time'][:16]}  "
              f"L{t['layers']} ${float(t['invested']):>8.2f} -> ${float(t['pnl']):>+7.2f} ({t['return_pct']}%)")
    
    print()
    print("=" * 80)
    print("  RECOMMENDATION")
    print("=" * 80)
    print(f"\n  Keep: {len(genuine)} genuine trades (${genuine_pnl:.2f} PnL)")
    print(f"  Review: {len(borderline)} borderline trades (${borderline_pnl:.2f} PnL)")
    print(f"  Remove: {len(phantom)} phantom trades (${phantom_pnl:.2f} PnL)")
    print(f"\n  Conservative equity: $50,000 + ${genuine_pnl:.2f} = ${50000 + genuine_pnl:.2f}")
    print(f"  With borderline:     $50,000 + ${genuine_pnl + borderline_pnl:.2f} = ${50000 + genuine_pnl + borderline_pnl:.2f}")

if __name__ == "__main__":
    analyze()
