[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "basis-sdk-python"
version = "0.1.0b1"
description = "Basis Ecosystem SDK for Python"
authors = [
  { name="Basis Ecosystem" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "web3>=6.0.0",
    "requests>=2.28.0",
    "eth-account>=0.8.0",
    "Pillow>=9.0.0"
]

[project.urls]
"Homepage" = "https://launchonbasis.com"

[tool.setuptools]
packages = ["basis", "basis.modules"]
